name: C/C++ CI

on:
  pull_request:
    branches: [main]

jobs:

  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: compile
      run: gcc MinesweeperRaidVer2.c
